### ISSUE TITLE
node.js:201 .. throw e; // process.nextTick error, or 'error' event on first tick

### ISSUE THREAD

**Issue by LarryEitel** [nezoomie/brunch-eggs-and-bacon#3]
larry@ubuntu:~/dev$ node -v
v0.6.10
larry@ubuntu:~/dev$ brunch -v
1.2.2
larry@ubuntu:~/dev$ brunch new try2 -s git://github.com/LarryEitel/brunch-eggs-and-bacon.git
08 Jun 16:30:00 - info: Created brunch directory layout
08 Jun 16:30:00 - info: Installing packages...
larry@ubuntu:~/dev$ cd try2/
larry@ubuntu:~/dev/try2$ brunch b

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:642:11)
    at Object.afterWrite [as oncomplete](net.js:480:18)

**Comment by nezoomie** [comment]
It seems to be a known issue with SASS brunch. (see https://github.com/nezoomie/brunch-eggs-and-bacon/issues/2 and https://github.com/brunch/sass-brunch/issues/5)

If you dont need to use SASS, removing it should fix the issue
