### ISSUE TITLE
brunch build error

### ISSUE THREAD

**Issue by denishoctor** [nezoomie/brunch-eggs-and-bacon#8]
After running 
`brunch new myProject -s github://nezoomie/brunch-eggs-and-bacon08`
`cd myProject` 
`brunch build` errored with:

`events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: write EPIPE
    at errnoException (net.js:781:11)
    at Object.afterWrite (net.js:594:19)``

I'm on OSx 10.7 with node v0.8.1. Have I missed something or is this a real issue?

**Comment by paulmillr** [comment]
It's a sass-brunch error. Seems you're using jRuby which is buggy or something like that. brunch/sass-brunch#5

**Comment by denishoctor** [comment]
Thanks for that, per eriwen's comment I ran `gem install sass` and it now builds.
